// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cuda_utils.proto

#ifndef PROTOBUF_INCLUDED_cuda_5futils_2eproto
#define PROTOBUF_INCLUDED_cuda_5futils_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cuda_5futils_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_cuda_5futils_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_cuda_5futils_2eproto();
namespace cudautils {
class matrixutils;
class matrixutilsDefaultTypeInternal;
extern matrixutilsDefaultTypeInternal _matrixutils_default_instance_;
}  // namespace cudautils
namespace google {
namespace protobuf {
template<> ::cudautils::matrixutils* Arena::CreateMaybeMessage<::cudautils::matrixutils>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cudautils {

// ===================================================================

class matrixutils :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cudautils.matrixutils) */ {
 public:
  matrixutils();
  virtual ~matrixutils();

  matrixutils(const matrixutils& from);

  inline matrixutils& operator=(const matrixutils& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  matrixutils(matrixutils&& from) noexcept
    : matrixutils() {
    *this = ::std::move(from);
  }

  inline matrixutils& operator=(matrixutils&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const matrixutils& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const matrixutils* internal_default_instance() {
    return reinterpret_cast<const matrixutils*>(
               &_matrixutils_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(matrixutils* other);
  friend void swap(matrixutils& a, matrixutils& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline matrixutils* New() const final {
    return CreateMaybeMessage<matrixutils>(nullptr);
  }

  matrixutils* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<matrixutils>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const matrixutils& from);
  void MergeFrom(const matrixutils& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(matrixutils* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 arrayleftrow = 1;
  bool has_arrayleftrow() const;
  void clear_arrayleftrow();
  static const int kArrayleftrowFieldNumber = 1;
  ::google::protobuf::int32 arrayleftrow() const;
  void set_arrayleftrow(::google::protobuf::int32 value);

  // required int32 arraycommom = 2;
  bool has_arraycommom() const;
  void clear_arraycommom();
  static const int kArraycommomFieldNumber = 2;
  ::google::protobuf::int32 arraycommom() const;
  void set_arraycommom(::google::protobuf::int32 value);

  // required int32 arrayrightcol = 3;
  bool has_arrayrightcol() const;
  void clear_arrayrightcol();
  static const int kArrayrightcolFieldNumber = 3;
  ::google::protobuf::int32 arrayrightcol() const;
  void set_arrayrightcol(::google::protobuf::int32 value);

  // optional int32 blockx = 4 [default = 16];
  bool has_blockx() const;
  void clear_blockx();
  static const int kBlockxFieldNumber = 4;
  ::google::protobuf::int32 blockx() const;
  void set_blockx(::google::protobuf::int32 value);

  // optional int32 blocky = 5 [default = 16];
  bool has_blocky() const;
  void clear_blocky();
  static const int kBlockyFieldNumber = 5;
  ::google::protobuf::int32 blocky() const;
  void set_blocky(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cudautils.matrixutils)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 arrayleftrow_;
  ::google::protobuf::int32 arraycommom_;
  ::google::protobuf::int32 arrayrightcol_;
  ::google::protobuf::int32 blockx_;
  ::google::protobuf::int32 blocky_;
  friend struct ::TableStruct_cuda_5futils_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// matrixutils

// required int32 arrayleftrow = 1;
inline bool matrixutils::has_arrayleftrow() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void matrixutils::clear_arrayleftrow() {
  arrayleftrow_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 matrixutils::arrayleftrow() const {
  // @@protoc_insertion_point(field_get:cudautils.matrixutils.arrayleftrow)
  return arrayleftrow_;
}
inline void matrixutils::set_arrayleftrow(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  arrayleftrow_ = value;
  // @@protoc_insertion_point(field_set:cudautils.matrixutils.arrayleftrow)
}

// required int32 arraycommom = 2;
inline bool matrixutils::has_arraycommom() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void matrixutils::clear_arraycommom() {
  arraycommom_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 matrixutils::arraycommom() const {
  // @@protoc_insertion_point(field_get:cudautils.matrixutils.arraycommom)
  return arraycommom_;
}
inline void matrixutils::set_arraycommom(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  arraycommom_ = value;
  // @@protoc_insertion_point(field_set:cudautils.matrixutils.arraycommom)
}

// required int32 arrayrightcol = 3;
inline bool matrixutils::has_arrayrightcol() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void matrixutils::clear_arrayrightcol() {
  arrayrightcol_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 matrixutils::arrayrightcol() const {
  // @@protoc_insertion_point(field_get:cudautils.matrixutils.arrayrightcol)
  return arrayrightcol_;
}
inline void matrixutils::set_arrayrightcol(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  arrayrightcol_ = value;
  // @@protoc_insertion_point(field_set:cudautils.matrixutils.arrayrightcol)
}

// optional int32 blockx = 4 [default = 16];
inline bool matrixutils::has_blockx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void matrixutils::clear_blockx() {
  blockx_ = 16;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 matrixutils::blockx() const {
  // @@protoc_insertion_point(field_get:cudautils.matrixutils.blockx)
  return blockx_;
}
inline void matrixutils::set_blockx(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  blockx_ = value;
  // @@protoc_insertion_point(field_set:cudautils.matrixutils.blockx)
}

// optional int32 blocky = 5 [default = 16];
inline bool matrixutils::has_blocky() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void matrixutils::clear_blocky() {
  blocky_ = 16;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 matrixutils::blocky() const {
  // @@protoc_insertion_point(field_get:cudautils.matrixutils.blocky)
  return blocky_;
}
inline void matrixutils::set_blocky(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  blocky_ = value;
  // @@protoc_insertion_point(field_set:cudautils.matrixutils.blocky)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cudautils

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_cuda_5futils_2eproto
