// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cuda_utils.proto

#include "cuda_utils.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace cudautils {
class matrixutilsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<matrixutils> _instance;
} _matrixutils_default_instance_;
}  // namespace cudautils
static void InitDefaultsmatrixutils_cuda_5futils_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cudautils::_matrixutils_default_instance_;
    new (ptr) ::cudautils::matrixutils();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cudautils::matrixutils::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_matrixutils_cuda_5futils_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmatrixutils_cuda_5futils_2eproto}, {}};

void InitDefaults_cuda_5futils_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_matrixutils_cuda_5futils_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_cuda_5futils_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_cuda_5futils_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_cuda_5futils_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_cuda_5futils_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, arrayleftrow_),
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, arraycommom_),
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, arrayrightcol_),
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, blockx_),
  PROTOBUF_FIELD_OFFSET(::cudautils::matrixutils, blocky_),
  0,
  1,
  2,
  3,
  4,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::cudautils::matrixutils)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cudautils::_matrixutils_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_cuda_5futils_2eproto = {
  {}, AddDescriptors_cuda_5futils_2eproto, "cuda_utils.proto", schemas,
  file_default_instances, TableStruct_cuda_5futils_2eproto::offsets,
  file_level_metadata_cuda_5futils_2eproto, 1, file_level_enum_descriptors_cuda_5futils_2eproto, file_level_service_descriptors_cuda_5futils_2eproto,
};

const char descriptor_table_protodef_cuda_5futils_2eproto[] =
  "\n\020cuda_utils.proto\022\tcudautils\"w\n\013matrixu"
  "tils\022\024\n\014arrayleftrow\030\001 \002(\005\022\023\n\013arraycommo"
  "m\030\002 \002(\005\022\025\n\rarrayrightcol\030\003 \002(\005\022\022\n\006blockx"
  "\030\004 \001(\005:\00216\022\022\n\006blocky\030\005 \001(\005:\00216"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_cuda_5futils_2eproto = {
  false, InitDefaults_cuda_5futils_2eproto, 
  descriptor_table_protodef_cuda_5futils_2eproto,
  "cuda_utils.proto", &assign_descriptors_table_cuda_5futils_2eproto, 150,
};

void AddDescriptors_cuda_5futils_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_cuda_5futils_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cuda_5futils_2eproto = []() { AddDescriptors_cuda_5futils_2eproto(); return true; }();
namespace cudautils {

// ===================================================================

void matrixutils::InitAsDefaultInstance() {
}
class matrixutils::HasBitSetters {
 public:
  static void set_has_arrayleftrow(matrixutils* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
  static void set_has_arraycommom(matrixutils* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_arrayrightcol(matrixutils* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_blockx(matrixutils* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_blocky(matrixutils* msg) {
    msg->_has_bits_[0] |= 0x00000010u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int matrixutils::kArrayleftrowFieldNumber;
const int matrixutils::kArraycommomFieldNumber;
const int matrixutils::kArrayrightcolFieldNumber;
const int matrixutils::kBlockxFieldNumber;
const int matrixutils::kBlockyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

matrixutils::matrixutils()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:cudautils.matrixutils)
}
matrixutils::matrixutils(const matrixutils& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&arrayleftrow_, &from.arrayleftrow_,
    static_cast<size_t>(reinterpret_cast<char*>(&blocky_) -
    reinterpret_cast<char*>(&arrayleftrow_)) + sizeof(blocky_));
  // @@protoc_insertion_point(copy_constructor:cudautils.matrixutils)
}

void matrixutils::SharedCtor() {
  ::memset(&arrayleftrow_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&arrayrightcol_) -
      reinterpret_cast<char*>(&arrayleftrow_)) + sizeof(arrayrightcol_));
  blockx_ = 16;
  blocky_ = 16;
}

matrixutils::~matrixutils() {
  // @@protoc_insertion_point(destructor:cudautils.matrixutils)
  SharedDtor();
}

void matrixutils::SharedDtor() {
}

void matrixutils::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const matrixutils& matrixutils::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_matrixutils_cuda_5futils_2eproto.base);
  return *internal_default_instance();
}


void matrixutils::Clear() {
// @@protoc_insertion_point(message_clear_start:cudautils.matrixutils)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    ::memset(&arrayleftrow_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&arrayrightcol_) -
        reinterpret_cast<char*>(&arrayleftrow_)) + sizeof(arrayrightcol_));
    blockx_ = 16;
    blocky_ = 16;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* matrixutils::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<matrixutils*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required int32 arrayleftrow = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_arrayleftrow(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // required int32 arraycommom = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_arraycommom(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // required int32 arrayrightcol = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_arrayrightcol(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 blockx = 4 [default = 16];
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_blockx(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional int32 blocky = 5 [default = 16];
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_blocky(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool matrixutils::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cudautils.matrixutils)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 arrayleftrow = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_arrayleftrow(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &arrayleftrow_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 arraycommom = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_arraycommom(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &arraycommom_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 arrayrightcol = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          HasBitSetters::set_has_arrayrightcol(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &arrayrightcol_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 blockx = 4 [default = 16];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {
          HasBitSetters::set_has_blockx(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blockx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 blocky = 5 [default = 16];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {
          HasBitSetters::set_has_blocky(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blocky_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cudautils.matrixutils)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cudautils.matrixutils)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void matrixutils::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cudautils.matrixutils)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 arrayleftrow = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->arrayleftrow(), output);
  }

  // required int32 arraycommom = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->arraycommom(), output);
  }

  // required int32 arrayrightcol = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->arrayrightcol(), output);
  }

  // optional int32 blockx = 4 [default = 16];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->blockx(), output);
  }

  // optional int32 blocky = 5 [default = 16];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->blocky(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cudautils.matrixutils)
}

::google::protobuf::uint8* matrixutils::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cudautils.matrixutils)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 arrayleftrow = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->arrayleftrow(), target);
  }

  // required int32 arraycommom = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->arraycommom(), target);
  }

  // required int32 arrayrightcol = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->arrayrightcol(), target);
  }

  // optional int32 blockx = 4 [default = 16];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->blockx(), target);
  }

  // optional int32 blocky = 5 [default = 16];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->blocky(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cudautils.matrixutils)
  return target;
}

size_t matrixutils::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:cudautils.matrixutils)
  size_t total_size = 0;

  if (has_arrayleftrow()) {
    // required int32 arrayleftrow = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arrayleftrow());
  }

  if (has_arraycommom()) {
    // required int32 arraycommom = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arraycommom());
  }

  if (has_arrayrightcol()) {
    // required int32 arrayrightcol = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arrayrightcol());
  }

  return total_size;
}
size_t matrixutils::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cudautils.matrixutils)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int32 arrayleftrow = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arrayleftrow());

    // required int32 arraycommom = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arraycommom());

    // required int32 arrayrightcol = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->arrayrightcol());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000018u) {
    // optional int32 blockx = 4 [default = 16];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->blockx());
    }

    // optional int32 blocky = 5 [default = 16];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->blocky());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void matrixutils::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cudautils.matrixutils)
  GOOGLE_DCHECK_NE(&from, this);
  const matrixutils* source =
      ::google::protobuf::DynamicCastToGenerated<matrixutils>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cudautils.matrixutils)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cudautils.matrixutils)
    MergeFrom(*source);
  }
}

void matrixutils::MergeFrom(const matrixutils& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cudautils.matrixutils)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      arrayleftrow_ = from.arrayleftrow_;
    }
    if (cached_has_bits & 0x00000002u) {
      arraycommom_ = from.arraycommom_;
    }
    if (cached_has_bits & 0x00000004u) {
      arrayrightcol_ = from.arrayrightcol_;
    }
    if (cached_has_bits & 0x00000008u) {
      blockx_ = from.blockx_;
    }
    if (cached_has_bits & 0x00000010u) {
      blocky_ = from.blocky_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void matrixutils::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cudautils.matrixutils)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void matrixutils::CopyFrom(const matrixutils& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cudautils.matrixutils)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool matrixutils::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void matrixutils::Swap(matrixutils* other) {
  if (other == this) return;
  InternalSwap(other);
}
void matrixutils::InternalSwap(matrixutils* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(arrayleftrow_, other->arrayleftrow_);
  swap(arraycommom_, other->arraycommom_);
  swap(arrayrightcol_, other->arrayrightcol_);
  swap(blockx_, other->blockx_);
  swap(blocky_, other->blocky_);
}

::google::protobuf::Metadata matrixutils::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cuda_5futils_2eproto);
  return ::file_level_metadata_cuda_5futils_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace cudautils
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::cudautils::matrixutils* Arena::CreateMaybeMessage< ::cudautils::matrixutils >(Arena* arena) {
  return Arena::CreateInternal< ::cudautils::matrixutils >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
